-- Reinitialise puis reimporte les donnees locales dans la base Railway.
-- Execute par le script src/scripts/import-production-data.js (pas par copier/coller dans un navigateur).

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `actualite_image`;
TRUNCATE TABLE `oeuvre`;
TRUNCATE TABLE `actualite`;
TRUNCATE TABLE `admin`;
TRUNCATE TABLE `artiste`;
TRUNCATE TABLE `association`;
TRUNCATE TABLE `message_contact`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `actualite` (`id`, `titre`, `contenu`, `image`, `categorie`, `date_evenement`, `lieu`, `a_la_une`, `published_at`) VALUES
(2, '2e Grand Salon des arts de la F.F.A.P.', 'La Federation Francaise des Arts Plastiques (FFAP) a le plaisir d\'annoncer la tenue du 2e Grand Salon des Arts, un rendez-vous incontournable dedie a la creation sous toutes ses formes.\r\n\r\nDu 4 au 7 mars 2027, le Forum du Casino de Hyeres deviendra un veritable laboratoire artistique ou se rencontreront talents confirmes, jeunes createurs, collectifs et passionnes d\'art contemporain. Apres le succes de sa premiere edition, le Salon revient avec une ambition renouvelee et une programmation enrichie.\r\n\r\nLes nouveautes de cette edition\r\n\r\nPour cette deuxieme edition, la FFAP innove et enrichit l\'experience des visiteurs avec plusieurs nouveautes marquantes :\r\n\r\n- Des stands habilles de tissus, proposes en deux harmonies de couleurs (tons chauds et tons froids), offrant une esthetique plus immersive et elegante, pensee pour sublimer chaque univers artistique.\r\n- Des demonstrations de Live Painting, permettant au public d\'assister en direct a la naissance d\'une oeuvre, dans une ambiance vibrante et participative.\r\n- Un espace Street Art, ou les artistes urbains realiseront des fresques et performances en temps reel.\r\n- La peinture sur vetement, nouvelle discipline mise a l\'honneur, fusionnant art visuel et expression textile.\r\n- Un defile exceptionnel, presentant les creations realisees pendant le salon : pieces uniques, vetements peints, silhouettes inspirees de l\'univers graphique de l\'affiche officielle, entre couleurs eclatantes, formes polygonales et energie contemporaine.\r\n\r\nUn large eventail de disciplines\r\n\r\nAu-dela de ces nouveautes, le Salon continuera d\'accueillir un large eventail de disciplines : peinture, sculpture, dessin, photographie, arts numeriques, installations, street art, ainsi que des espaces dedies aux associations et createurs independants.\r\n\r\nAvec cette edition renouvelee, la FFAP affirme sa volonte de celebrer l\'art sans limites, de favoriser les rencontres, et d\'offrir au public une experience artistique riche, vivante et audacieuse.\r\n\r\nInformations pratiques\r\n\r\nLe Salon est ouvert au public du 4 au 7 mars 2027, au Forum du Casino de Hyeres. Horaires, tarifs et modalites d\'inscription pour les exposants seront precises prochainement sur le site de la FFAP.', '/uploads/1787236807707.png', 'evenement', '2027-03-03', 'Forum du Casino de Hyeres', 0, '2026-08-20 14:40:07'),
(3, 'Sortie Avignon — Le palais des Papes', 'La Federation Francaise des Arts Plastiques a egalement organise une sortie culturelle a Avignon visiter le Palais des Papes, reunissant un groupe d\'adherents autour d\'une journee de decouverte artistique et patrimoniale. Entre patrimoine historique, lieux emblematiques et espaces d\'exposition, cette escapade a permis d\'explorer la richesse culturelle de la ville.\r\n\r\nDans une atmosphere conviviale, les participants ont pu echanger autour des oeuvres, des lieux visites et de leurs propres pratiques artistiques. Cette sortie a ete l\'occasion de nourrir la curiosite, de partager des impressions et de renforcer les liens au sein de la Federation.\r\n\r\nEn proposant ce type de rendez-vous, la Federation Francaise des Arts Plastiques poursuit son engagement en faveur de la rencontre entre les artistes, les amateurs et les lieux de culture. D\'autres sorties et evenements seront programmes afin de continuer a offrir des moments de decouverte, de dialogue et de plaisir partage autour de l\'art.', '/uploads/1787241074846.png', 'sorties', '2026-01-17', 'Avignon', 0, '2026-08-20 15:45:22'),
(4, 'Sortie au Chateau La Coste', 'Le 25 octobre 2025, la Federation Francaise des Arts Plastiques a organise une journee de decouverte au Chateau La Coste, reunissant un groupe de cinquante participants. Dans un cadre melant art, architecture et nature, cette sortie a ete l\'occasion de partager un moment convivial autour de la creation contemporaine.\r\n\r\nLa meteo particulierement agreable a permis de profiter pleinement du site, des promenades en exterieur et des oeuvres disseminees dans le paysage. Entre sculptures monumentales, installations et expositions, les participants ont pu faire de belles decouvertes artistiques tout au long du parcours.\r\n\r\nCette journee a egalement favorise les echanges entre artistes et amateurs d\'art, dans un esprit de rencontre et de partage. Chacun est reparti enrichi de nouvelles inspirations, de points de vue croises et du souvenir d\'un moment chaleureux passe ensemble.\r\n\r\nEn proposant ce type de sortie culturelle, la Federation Francaise des Arts Plastiques poursuit sa mission de valorisation de la creation artistique et de mise en lien des publics avec des lieux d\'art majeurs.', '/uploads/1787388818304.jpeg', 'sorties', '2025-10-25', 'Chateau La Coste', 0, '2026-08-22 08:53:38'),
(5, 'Salon des Arts Contemporains — Hyeres', 'Du 30 avril au 3 mai 2026 — Forum du Casino a Hyeres\r\n\r\nLa Federation Francaise des Arts Plastiques organise son Salon des Arts Contemporains au Forum du Casino a Hyeres, avenue Ambroise Thomas, du 30 avril au 3 mai 2026. Cet evenement rassemblera peintres, sculpteurs, dessinateurs, aquarellistes, photographes et artisans d\'art venus de toute la France pour quatre jours de creation et de rencontres avec le public.\r\n\r\nLes invitees d\'honneur de cette edition seront les Bombaspheres, un collectif d\'artistes parisiennes specialise dans le street art. Chaque jour, un show unique sera propose, avec des performances en direct et la realisation d\'oeuvres sur place, offrant aux visiteurs l\'occasion d\'assister au travail des artistes en temps reel.\r\n\r\nLe salon sera ouvert de 10h a 19h, avec une entree gratuite, afin de permettre au plus grand nombre de decouvrir la diversite des pratiques artistiques contemporaines. Une restauration sur place sera egalement proposee pour profiter pleinement de la journee.', '/uploads/1787390669373.jpg', 'evenement', '2026-04-30', 'Forum du Casino, avenue Ambroise Thomas, Hyeres', 0, '2026-08-22 09:24:29');

INSERT INTO `admin` (`id`, `email`, `mot_de_passe`, `created_at`) VALUES
(1, 'ffap.83@gmail.com', '$2a$10$Pn0qmNdWkBgdZwROLksA.eKA7CDTkaxnXXAq7cX5Up0MFKBfF0m5e', '2026-08-16 16:22:42');

INSERT INTO `artiste` (`id`, `nom`, `discipline`, `bio`, `photo`, `created_at`) VALUES
(1, 'Martine de Santis', 'Peinture, Sculpture', 'Depuis sa retraite en 2015, Martine de Santis consacre une grande partie de son temps a ses passions artistiques : la peinture et la sculpture. Ces deux pratiques, qu\'elle mene en parallele, lui permettent d\'exprimer sa creativite tout en continuant, a chaque oeuvre, a explorer de nouvelles techniques et de nouvelles sensibilites.\r\n\r\nPour Martine, creer est avant tout une source de plaisir, d\'evasion et de rencontres. Chaque toile ou sculpture est une nouvelle aventure, l\'occasion de traduire une emotion, une intuition ou un regard singulier sur le monde qui l\'entoure.\r\n\r\nPresidente des Artistes Gardeens\r\n\r\nMartine de Santis preside l\'association Les Artistes Gardeens, basee a La Garde, dans le Var. L\'association a pour vocation de promouvoir l\'art sous toutes ses formes — peinture, aquarelle, huiles, modelage, dessin, vitraux — a travers des cours, des ateliers libres et des expositions organisees tout au long de l\'annee, notamment lors du Salon de Printemps et des expositions a la salle Gerard Philipe.\r\n\r\nA la tete de cette structure, elle coordonne l\'organisation des activites, des expositions et des projets de l\'association, tout en favorisant les echanges entre les membres et les clubs partenaires. Cet engagement associatif lui permet de partager sa passion de l\'art avec un large public et de contribuer activement a la vie culturelle de sa commune.\r\n\r\nPresider une association d\'artistes est pour elle une experience aussi enrichissante que sa pratique personnelle : elle y trouve un sens supplementaire a son engagement, entre transmission, organisation et vie collective autour de la creation.', '/uploads/1787145689750.jpg', '2026-08-18 12:34:20'),
(2, 'Christian Disty', 'Peinture', 'Christian Disty est ne a Bruxelles, en Belgique, le 18 janvier 1950. Installe en France depuis 2012, il vit a Bormes-les-Mimosas, ou il poursuit son parcours artistique.\r\n\r\nArtiste depuis plus de cinquante ans, il a mene l\'essentiel de sa carriere dans l\'univers de la magie, presentant ses spectacles a travers le monde aux cotes de son epouse, egalement son assistante de scene.\r\n\r\nDe la magie a la peinture\r\n\r\nA la retraite, il realise un reve de longue date en se consacrant a la peinture. Cette nouvelle passion l\'amene a rapprocher ses deux univers artistiques : la magie et les arts plastiques. De cette rencontre naissent les Tableaux Magiques, des oeuvres concues pour la scene, permettant aux magiciens de faire apparaitre ou disparaitre des objets ou des animaux directement depuis le tableau.\r\n\r\nAu-dela de ce concept unique, Christian Disty developpe une peinture plus personnelle, portee notamment par une serie sur le theme des drapes et un travail exploratoire autour de la resine. Il realise egalement des portraits sur commande d\'apres photographie, dans un style figuratif sensible qui prolonge, hors de la scene, son gout pour l\'illusion et le mouvement.\r\n\r\nEn 2015, ses creations sont recompensees lors du championnat du monde de magie par le prix du plus bel effet magique au monde en originalite.\r\n\r\nUn engagement au service des arts plastiques\r\n\r\nEngage dans la promotion des arts plastiques, Christian Disty devient president du Mouvement des Arts en 2019, avant d\'accompagner sa transformation en Federation des Arts Plastiques en 2025. Son action vise a soutenir les artistes a travers des evenements, conferences, ateliers et rencontres culturelles.\r\n\r\nSa devise resume son engagement : « Unissons nos forces pour valoriser les arts plastiques ! »', '/uploads/1787145689777.jpeg', '2026-08-19 13:14:47'),
(3, 'Lise Oerlemans', 'Peinture', 'Lise Oerlemans vit et travaille a Hyeres, ou elle est arrivee il y a plus de trente-cinq ans. Au fil du temps, elle y a construit un ancrage personnel et artistique fort, nourri par la lumiere et les paysages de la region.\r\n\r\nGuidee dans ses debuts par une artiste peintre qui lui a transmis l\'importance des jeux de lumiere, des ombres, du mouvement et des vibrations, Lise a progressivement affirme sa propre ecriture. Son travail se concentre aujourd\'hui sur la peinture a l\'huile au couteau, une technique qu\'elle utilise pour traduire l\'energie et la matiere de ses sujets.\r\n\r\nSes toiles representent principalement des paysages, inspires par ses voyages et ses rencontres avec la nature. Chaque oeuvre est l\'occasion de saisir une atmosphere, une lumiere fugace ou une emotion liee a un lieu, que Lise retranscrit avec une touche dynamique et une palette sensible.\r\n\r\nUne presence artistique ancree dans la duree\r\n\r\nInvestie de longue date dans la vie artistique locale, Lise Oerlemans a longtemps participe aux activites du Mouvement des Arts, aujourd\'hui devenu la Federation Francaise des Arts Plastiques, dont la transformation a ete officialisee en 2025. Elle expose chaque annee au Forum du Casino de Hyeres et est egalement presente toute l\'annee a la galerie de Giens, poursuivant ainsi un dialogue continu avec le public.', '/uploads/1787145689782.jpeg', '2026-08-19 13:14:47');

INSERT INTO `association` (`id`, `nom`, `logo`, `description`, `lien_externe`, `created_at`) VALUES
(2, 'Les Artistes Gardeens', '/uploads/1787326213478.jpg', 'Presidee par Martine de Santis\r\n\r\nL\'Association Les Artistes Gardeens est un exemple vivant de la maniere dont un atelier d\'art local peut stimuler la creativite et enrichir durablement la vie culturelle. Cette association offre bien plus qu\'un simple lieu d\'expression artistique : elle rassemble une veritable communaute ou artistes et amateurs d\'art se rencontrent pour apprendre, creer et partager leur passion.\r\n\r\nUn lieu dedie a l\'apprentissage et a la pratique artistique\r\nL\'association accueille chaleureusement les artistes de tous niveaux, des debutants aux createurs confirmes. Elle propose des ateliers, des cours et des seances de pratique libre permettant d\'explorer differentes disciplines telles que la peinture, la sculpture, le dessin et les techniques mixtes. Cette approche pratique encourage l\'experimentation, le developpement personnel et la progression artistique.\r\n\r\nElle met notamment a disposition : des ateliers adaptes a tous les niveaux, du materiel et des outils de qualite professionnelle, ainsi que l\'accompagnement d\'artistes et d\'intervenants experimentes.\r\n\r\nEn privilegiant la pratique, l\'association permet a chacun de developper ses competences tout en renforcant sa confiance en lui. A titre d\'exemple, un recent atelier consacre a la peinture a initie les participants a la theorie des couleurs et a la composition, avant de se conclure par une exposition collective mettant en valeur les oeuvres realisees.\r\n\r\nUne dynamique humaine et collective\r\nL\'un des plus grands atouts de l\'association reside dans sa capacite a creer une veritable dynamique humaine. Les artistes travaillent souvent de maniere isolee ; cet atelier leur offre un espace d\'echange, de collaboration et de dialogue. Les critiques collectives, les expositions et les rencontres conviviales permettent aux membres de partager leurs experiences et leur passion.\r\n\r\nUne ouverture vers le grand public\r\nL\'association s\'adresse egalement au grand public en organisant regulierement des expositions ouvertes a tous. Ces manifestations permettent aux artistes de presenter leurs creations en dehors de l\'atelier et favorisent les echanges avec les habitants autour de l\'art et de la culture.\r\nN\'hesitez pas a decouvrir ou a rejoindre l\'association afin de vivre pleinement l\'experience enrichissante que l\'art peut offrir a chacun.', NULL, '2026-08-21 15:30:13'),
(3, 'La Palette Valettoise', '/uploads/1787327364113.jpg', '83160 La Valette-du-Var\r\n\r\nUne histoire ancree dans la commune\r\nLa Palette Valettoise est une association Loi 1901, fondee en 1966 a La Valette-du-Var. C\'est la plus ancienne association de la commune. Depuis sa creation, les peintres amateurs peuvent donner libre cours a leur inspiration et a leur passion.\r\n\r\n« La Peinture est une poesie qui se voit. » — Leonard de Vinci\r\n\r\nNotre mission\r\nL\'association a pour objet de regrouper des artistes afin de favoriser les arts plastiques, en particulier la peinture, et toutes les activites qui s\'y rapportent, suivant les rythmes et les envies de chacune et de chacun. Pour cela, elle propose une information reguliere aupres de ses adherents, ainsi que l\'organisation d\'expositions, d\'echanges et de voyages culturels.\r\nNotre public se compose d\'adherents qui sont tous des peintres amateurs.\r\n\r\nLa vie de l\'atelier\r\nL\'atelier est ouvert trois apres-midis par semaine — le lundi, le mercredi et le vendredi, de 14h00 a 17h30. Chaque peintre dispose d\'un espace dedie et peut laisser l\'ensemble de son materiel sur place, dans des locaux adaptes ou regne une ambiance detendue, propice a la concentration. Des intervenants sont regulierement sollicites pour dispenser des cours de dessin et de peinture.\r\n\r\nNos rendez-vous et partenariats\r\nL\'association organise actuellement une exposition annuelle au printemps, a la Salle du Lavoir, a La Valette-du-Var. Elle est par ailleurs sollicitee plusieurs fois par an par la Municipalite pour participer a certains evenements (Telethon, Octobre Rose...) et organiser des ateliers de peinture pour les enfants, a l\'occasion de Noel, du Carnaval ou de la Fete de la Fraise. Ces ateliers remportent chaque fois un franc succes !\r\n\r\nNous rejoindre\r\nPeintres amateurs, debutants ou confirmes : La Palette Valettoise vous accueille dans un cadre convivial et stimulant, riche de pres de soixante ans d\'histoire.\r\nN\'hesitez pas a venir decouvrir l\'atelier et a rejoindre notre communaute de passionnes.', NULL, '2026-08-21 15:30:13'),
(4, 'Couleurs Revestoises', '/uploads/1787326213505.png', 'Association d\'artistes du Revest-les-Eaux', NULL, '2026-08-21 15:30:13');

INSERT INTO `message_contact` (`id`, `nom`, `email`, `telephone`, `message`, `statut`, `created_at`) VALUES
(1, 'Marie Dupont', 'marie@exemple.fr', NULL, 'Bonjour, je souhaite des informations sur l\'adhésion.', 'nouveau', '2026-08-18 13:16:50');

INSERT INTO `oeuvre` (`id`, `artiste_id`, `titre`, `image`, `description`, `created_at`) VALUES
(1, 2, 'Lion', '/uploads/1787155189584.png', NULL, '2026-08-19 15:59:49'),
(2, 2, 'Regard de louve', '/uploads/1787155189620.png', NULL, '2026-08-19 15:59:49'),
(3, 1, 'Sculpture en cours de creation', '/uploads/1787235781861.png', NULL, '2026-08-20 14:23:01'),
(4, 1, 'Gorille', '/uploads/1787235781889.jpg', NULL, '2026-08-20 14:23:01');
